apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: stripe-frontend-build
  labels:
    app: stripe-payment
    component: frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/husain-alqassab/stripe-payment-app-sandbox.git
      ref: main
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: stripe-frontend:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: stripe-frontend
  labels:
    app: stripe-payment
    component: frontend
spec:
  lookupPolicy:
    local: true
